Add dhis2-admin as service to set-credential

diff --git a/setup/service/dhis2-set-credential b/setup/service/dhis2-set-credential
--- a/setup/service/dhis2-set-credential
+++ b/setup/service/dhis2-set-credential
@@ -10,7 +10,7 @@ SERVICE=$1
 CONTAINER_NAME=$2
 GLOWROOT_VERSION="0.13.6"
 #VALID_SERVICES=$(lxc list -c n -f csv | grep -v 'postgres\|proxy' | tr '\n' ' ')
-VALID_SERVICES=("munin" "glowroot" "elasticsearch")
+VALID_SERVICES=("munin" "glowroot" "elasticsearch" "dhis2-admin")
 
 # Help text for this script
 function usage {
@@ -45,6 +45,54 @@ function save_munin_creds() {
   # write creds to file
   local json_str='{"service":"munin","username":"admin","password":"'${passwd}'"}'
   save_creds $json_str
+}
+
+function save_dhis2_creds() {
+  local readonly passwd="${1}"
+  local old_user old_password admin_info user_json uid rid json_str ret
+  local readonly creds=$(get_creds ${CONTAINER_NAME}-dhis2-admin)
+
+  if [[ "${creds}" ]]; then
+    user=$(echo ${creds} | jq -r .username)
+    old_password=$(echo ${creds} | jq -r '.password')
+  else
+    user="admin"
+    old_password="district"
+  fi
+
+  admin_info=$(lxc exec $CONTAINER_NAME -- curl -s --fail -k -u "$user":"${old_password}" "http://localhost:8080/${CONTAINER_NAME}/api/me")
+  ret=$?
+
+  if [ $ret -ne 0 ]; then
+    log_error "Error getting information about current user (curl exit code: $ret). Exiting"
+    return 1
+  fi
+
+  uid=$(jq -r .id <<< ${admin_info})
+  rid=$(jq -r .userRoles[].id <<< ${admin_info})
+
+  user_json='{"id":"%s","username":"admin","surname":"admin","firstName":"admin", "name":"admin admin","userRoles":[{"id":"%s"}],"userCredentials":{"uid":"%s","username":"%s","password":"%s"}}\n'
+  user_data=$(printf "${user_json}" "$uid" "$rid" "$uid" "$user" "${passwd}")
+
+  lxc exec $CONTAINER_NAME -- curl --connect-timeout 5 -k -u "$user":"${old_password}" -XPUT -H 'Content-Type: application/json' "http://localhost:8080/${CONTAINER_NAME}/api/users/${uid}" -d "${user_data}"
+  ret=$?
+
+  if [ $ret -ne 0 ]; then
+    log_error "Error in changing user's password (curl exit code: $ret). Exiting"
+    return 1
+  fi
+
+  json_str='{"service":"'${CONTAINER_NAME}'-dhis2-admin","username":"'${user}'","password":"'${passwd}'"}'
+
+  save_creds ${json_str}
+
+  echo " "
+  echo "Credentials have been set:"
+  echo "========================="
+  echo "Instance: ${CONTAINER_NAME}"
+  echo "Service: ${CONTAINER_NAME}-dhis2-admin"
+  echo "Username: $user"
+  echo "Password: ${passwd}"
 }
 
 function save_glowroot_creds() {
@@ -135,7 +183,11 @@ select yn in "Yes" "No"; do
       read PASSWD
       break;;
     No )
-      PASSWD=$(openssl rand -hex 24)
+      if [[ "$SERVICE" == "dhis2-admin" ]]; then
+        PASSWD=$(tr -dc 'A-Za-z0-9!@#^*()-+_?%=.<,>;:{}[]/' < /dev/urandom | head -c 24)
+      else
+        PASSWD=$(openssl rand -hex 24)
+      fi
       break;;
   esac
 done
@@ -149,6 +201,9 @@ case $SERVICE in
     ;;
   "elasticsearch" )
     save_es_creds $PASSWD
+    ;;
+  "dhis2-admin" )
+    save_dhis2_creds "${PASSWD}"
     ;;
   * ) # this shouldn't trigger but adding just in case
     log_error "Service $SERVICE not supported. Quitting."
