Add support for dhis2-admin creds for older DHIS2 versions with different user formats

diff --git a/setup/service/dhis2-set-credential b/setup/service/dhis2-set-credential
--- a/setup/service/dhis2-set-credential
+++ b/setup/service/dhis2-set-credential
@@ -69,11 +69,21 @@ function save_dhis2_creds() {
   fi
 
   uid=$(jq -r .id <<< ${admin_info})
-  rid=$(jq -r .userRoles[].id <<< ${admin_info})
+  rid=$(jq -r '. | select(.userRoles != null).userRoles[].id // empty' <<< ${admin_info})
 
-  user_json='{"id":"%s","username":"admin","surname":"admin","firstName":"admin", "name":"admin admin","userRoles":[{"id":"%s"}],"userCredentials":{"uid":"%s","username":"%s","password":"%s"}}\n'
+  if [[ "$rid" ]]; then
+    user_json='{"id":"%s","username":"admin","surname":"admin","firstName":"admin", "name":"admin admin","userRoles":[{"id":"%s"}],"userCredentials":{"uid":"%s","username":"%s","password":"%s"}}\n'
+  else
+    rid=$(jq -r '.userCredentials.userRoles[].id // empty' <<< ${admin_info})
+    user_json='{"id":"%s","username":"admin","surname":"admin","firstName":"admin", "name":"admin admin","userCredentials":{"userRoles":[{"id":"%s"}], "userInfo": {"id":"%s"},"username":"%s","password":"%s"}}\n'
+  fi
+
+  if ! [[ "$rid" ]]; then
+    log_error "Error getting the user role ID. Exiting"
+    return 1
+  fi
+
   user_data=$(printf "${user_json}" "$uid" "$rid" "$uid" "$user" "${passwd}")
-
   lxc exec $CONTAINER_NAME -- curl --fail --connect-timeout 5 -k -u "$user":"${old_password}" -XPUT -H 'Content-Type: application/json' "http://localhost:8080/${CONTAINER_NAME}/api/users/${uid}" -d "${user_data}"
   ret=$?
 
