set-elasticsearch configures filebeat now even if already installed (was skipping before)

diff --git a/setup/service/dhis2-set-elasticsearch b/setup/service/dhis2-set-elasticsearch
--- a/setup/service/dhis2-set-elasticsearch
+++ b/setup/service/dhis2-set-elasticsearch
@@ -48,25 +48,25 @@ if ! [ "$(lxc exec $container_name -- dpkg -l | grep filebeat)" ]; then
   log_info "Retrieving filebeat $FILEBEAT_VERSION ($arch)"
 
   if ! [ -f "${TMP_FILEBEAT}" ]; then
-      curl -s -L -o $TMP_FILEBEAT -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-$FILEBEAT_VERSION-$arch.deb || { log_error "Cannot download filebeat. Quitting"; exit 1; }
+    curl -s -L -o $TMP_FILEBEAT -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-$FILEBEAT_VERSION-$arch.deb || { log_error "Cannot download filebeat. Quitting"; exit 1; }
   fi
 
   log_info "Installing filebeat"
   lxc file push $TMP_FILEBEAT ${container_name}/${TMP_FILEBEAT}
   lxc exec $container_name -- dpkg -i $TMP_FILEBEAT
   lxc exec $container_name -- rm -rf $TMP_FILEBEAT
-
-  log_info "Configuring filebeat"
-  lxc file push ./etc/filebeat.yml ${container_name}/etc/filebeat/
-  lxc exec $container_name -- chown root.root /etc/filebeat/filebeat.yml
-  lxc exec $container_name -- chmod go-w /etc/filebeat/filebeat.yml
-
-  lxc exec $container_name -- sed -i -e "s/ES_HOST/$IPREGEX/" /etc/filebeat/filebeat.yml
-  lxc exec $container_name -- sed -i -e "s/changeme/$ES_USER_PWD/" /etc/filebeat/filebeat.yml
-  lxc exec $container_name -- sed -i -e "s/LOCAL_HOST/$container_name/" /etc/filebeat/filebeat.yml
-
-  lxc exec $container_name -- systemctl enable --now filebeat
-  log_info "Filebeat configured. All good"
 else
-  log_warn "Filebeat already installed. Skipping"
+  log_info "Filebeat already installed"
 fi
+
+log_info "Configuring filebeat"
+lxc file push ./etc/filebeat.yml ${container_name}/etc/filebeat/
+lxc exec $container_name -- chown root.root /etc/filebeat/filebeat.yml
+lxc exec $container_name -- chmod go-w /etc/filebeat/filebeat.yml
+
+lxc exec $container_name -- sed -i -e "s/ES_HOST/$IPREGEX/" /etc/filebeat/filebeat.yml
+lxc exec $container_name -- sed -i -e "s/changeme/$ES_USER_PWD/" /etc/filebeat/filebeat.yml
+lxc exec $container_name -- sed -i -e "s/LOCAL_HOST/$container_name/" /etc/filebeat/filebeat.yml
+
+lxc exec $container_name -- systemctl enable --now filebeat
+log_info "Filebeat configured. All good"
